### ISSUE TITLE
is There any way to change size of print paper on ngx-print-element?

### ISSUE THREAD

**Issue by CeidAbbas** [id1945/ngx-print-element#9]

**Comment by id1945** [comment]
### Check out some of the links below! 
https://pagedjs.org/documentation/5-web-design-for-print/
https://developer.mozilla.org/en-US/docs/Web/CSS/@page/size

```css
@media print {
  /* Use A4 paper in landscape orientation */
  @page {
    size: A4 landscape;
  }
}
```
